config/routes.rb
require 'sidekiq/web'

ThreetapsPostingApi::Application.routes.draw do
  mount Sidekiq::Web, at: "/admin/sidekiq"

  get '/proxy' =>  'proxies#proxy'
  post '/proxy' =>  'proxies#proxy'

  get "/login" => "clients#login"
  post "/login" => "clients#authenticate"
  get '/logout' => "clients#logout"

  get "request_builders/locations" => "request_builders#locations"
  get "request_builders/polling" => "request_builders#polling"
  get "request_builders/reference_api_request" => "request_builders#reference_api_request"

  get "report_data" => "source_category_statistics#index"
  post 'stats' => 'stats#create'

  get '/sources/zip_stats(.:format)' => "zips#old_date_zips"

  get "annotations" => "annotations#index"
  get "available_annotations" => 'annotations_locations#index'
  get 'bckpg_process' => "bckpgs#bckpg_process"
  root 'postings#create', via: :post
  get '/' => 'payment_home#index'
  get 'anchor' => 'postings#anchor'
  get 'anchor2' => 'postings#anchor2'
  get 'poll' => 'postings#poll'
  get 'postings/:id' => 'postings#show'
  get 'pages/health' => 'pages#health'
  scope 'html-postings' do
    post 'craig' => 'html_postings#craig'
  end

  post '/scrapers/info' => 'scraper_infos#create'

  #match 'post_single', to: 'postings#options', via: [:options], constraints: {method: 'OPTIONS'}
  match 'post_single', to: 'postings#create', via: [:post, :options]
  #post 'post_single' => 'postings#create'
  #match 'post_multi', to: 'postings#create', via: [:post, :options]
  post 'post_multi' => 'postings#create'
  post 'post_raw_single' => 'postings#raw_create'
  post 'post_raw_multi' => 'postings#raw_create'

  get "/payment_home" => 'payment_home#index'
  get '/contracts' => 'payment_home#contracts'
  get "/contracts_rates" => 'payment_home#client_rates'
  get "/category_group/:category_group" => 'payment_home#categories', as: :category_group

  resources :demand_source_rates, only: [:index, :edit, :update, :create]

  resources :posting_examples, only: [:new, :create]
  resources :html_examples, only: [:new, :create]
  #get 'admin' => 'admin#index'
  namespace :admin do
    get "posting_stats" => 'posting_stats#index'
    get "insert_profilers" => 'insert_profilers#index'
    get "system_events" => 'system_events#index'
    get "system_events/show" => 'system_events#show'
    get '/' => 'home#index'
    put '/' => 'home#update'

    get '/accounts/refresh' => 'accounts#refresh_approved', as: 'refresh_approved_accounts'

    resources :annotations do
      collection do
        get 'csv' => 'annotations#csv_export', as: 'csv'
      end
    end

    resources :calculate_annotations, only: [ :index ] do
      collection do
        put '/' => 'calculate_annotations#update'
      end
    end

    resources :quality_statistics, only: [ :index ] do
      collection do
        get '/incomplete_annotations' => 'quality_statistics#incomplete_annotations', as: 'incomplete_annotations'
        get '/incomplete_fields' => 'quality_statistics#incomplete_fields', as: 'incomplete_fields'
        match '/with_:attribute' => 'quality_statistics#postings_with_quality', via: [ :get ], constraints: { attribute: /(fields|annotations)_quality/ }, as: 'postings_with_quality'
      end
    end

    get "/annotations_qualities" => 'quality_statistics#annotations_qualities'
    get "/fields_qualities" => 'quality_statistics#fields_qualities'

    resources :converters
    resources :response_counts

    resources :proxy_ips, only: :index

    resources :statistics, only: [ :index ] do
      collection do
        get '/live_data' => 'statistics#live_data', as: 'live_data'
        get '/total_data' => 'statistics#total_data', as: 'total_data'
        get '/us_borders(.:format)' => 'statistics#us_borders'
        get '/states_data(.:format)' => 'statistics#states_data'
        get '/antengo' => 'statistics#antengo', as: 'antengo'
      end

    end

    resources :empty_timestamps, only: [ :index ]
    get "/empty_ids" => "empty_timestamps#show_ids"

    get '/live_lovely' => "live_lovelies#index", as: :live_lovelies

    resources :payment_rates, only: [ :index, :edit, :update ]
    post 'update_categories_rates' => 'payment_rates#update_categories_rates'

    resources :payment_reports, only: :index

    resources :source_accounts, only: :index

    resources :latency_statistics, only: :index

    post "update_latency_offset" => "latency_statistics#update_latency_offset"

    get "latency_hourly" => "latency_statistics#latency_hourly"
    get "latency_daily" => "latency_statistics#latency_daily"
    get "latency_monthly" => "latency_statistics#latency_monthly"
    get "latency_day_hourly" => "latency_statistics#latency_day_hourly"

    get "update_sources" => "backpage_sources#update_sources"
    get "update_file" => "backpage_sources#update_file"
    get "filter_by_address" => "response_counts#filter_by_address"
    get "filter_by_date" => "response_counts#filter_by_date"
    resources :sources, only: :index do
      collection do
        get ":source" => "sources#zips_by_source", as: 'zips_by_source'
        get "/carmakers/:source" => "sources#carmakers_by_source", as: 'carmakers_by_source'
      end
    end

    resources :notifications, only: [:index, :update]
    resources :html_examples, path: 'html-examples', only: [:index, :show] do
      member do
        delete '/' => 'html_examples#reject'
        post '/' => 'html_examples#accept'
        put '/' => 'html_examples#ready'
      end
    end
    scope 'compliances', as: :compliances do
      get '/' => 'compliances#index'
      post '/' => 'compliances#index'
    end

    scope 'parsing', as: :parsing do
      get '/' => 'parsing#index'
      get '/:source' => 'parsing#show', as: :show
      get '/mockup' => 'parsing#show' #trick!?
      post '/' => 'parsing#create'
    end

    resources :exceptions, only: :index do
      # get '/' => 'exceptions#index'
      member do
        get 'retry_last_posting'
        get 'retry_all_postings'
        get 'delete'
        get 'details', as: :details
      end
    end

    resources :auth_tokens

    get '/token_settings/:id' => "auth_tokens#settings", as: :token_settings
    get '/generate_token' => "auth_tokens#generate_token", as: :generate_token

    get '/scrapers/info' => "scraper_infos#index", as: :scraper_infos
    # resources :scraper_infos, only: :index

    scope 'partitions', as: :partitions do
      get '/' => 'partitions#index'
      post '/' => 'partitions#index'
    end
  end
end

app/controllers/admin/latency_statistics_controller.rb
class Admin::LatencyStatisticsController < Admin::ChartController
  add_breadcrumb :latencies, :admin_statistics_path

  before_action :default_dates, only: :index

  def index
    @latency_offset = RedisHelper.get_redis.get("latency_offset") || 100

    periods = [:hourly, :daily, :monthly]

    @series = {}    

    periods.each{|period| @series[period] = LatencyHourlyStatistic.send(period)}

    @chart_options = default_chart_options.merge(latency_chart_options)
  end
  
  def update_latency_offset
    RedisHelper.get_redis.set("latency_offset", latency_params[:latency_offset].to_i)
    render json: {status: "ok"}.to_json
  end

  def latency_hourly
    render json: LatencyHourlyStatistic.hourly(DateTime.parse(latency_params[:date] + ":00:00 GMT-04:00", "%Y-%m-%d %H:%M %Z")).to_json 
  end

  def latency_daily
    render json: LatencyHourlyStatistic.daily(DateTime.parse(latency_params[:date])).to_json
  end

  def latency_monthly
    render json: LatencyHourlyStatistic.monthly(DateTime.parse(latency_params[:date] + "-01")).to_json
  end

  def latency_day_hourly
    render json: LatencyHourlyStatistic.day_hourly(DateTime.parse(latency_params[:date])).to_json
  end  

  private

  def default_dates
    @default_hour = (Time.now - 1.hour).strftime("%H")
    @default_hour_day = Time.now.strftime("%Y-%m-%d")

    @min_day = StatisticByLatency.min_day
    @max_day = StatisticByLatency.max_day
    @default_day = (Time.now - 1.day).strftime("%Y-%m-%d")
    
    
    @min_month = StatisticByLatency.min_month
    @max_month = StatisticByLatency.max_month
    @default_month = Time.now.strftime("%Y-%m")
  end  

  def latency_params
    params.permit(:latency_offset, :date)
  end 

  def latency_chart_options
    {
      plotOptions: {
        column: {
          allowPointSelect: true,
          colorByPoint: true,
          colors: ['#7cb5ec', '#434348', '#90ed7d', '#f7a35c', '#8085e9', '#f15c80', '#e4d354', '#8085e8', '#8d4653', '#91e8e1']
        }
      }
    }
  end 

end 

app/views/admin/latency_statistics/_change_offset.html.haml
%div{style: "height: 40px"}
  .alert{class: "alert-success hide text-left"}
    Saved
.modal-body-content
  %strong
    Latency offset:
  = range_field_tag :latency_offset  

app/views/admin/latency_statistics/_chart.html.haml
.row-fluid.total
  .span2
    = render partial: "date_#{title}"
  .span10.text-center{class: "#{title}"}
    %h3
      = title.to_s.titleize
      latency statistic 
    = column_chart latencies, @chart_options

app/views/admin/latency_statistics/_date_daily.html.haml
.form-group
  #datepicker_daily{class: "input-append date"}
    = text_field_tag :date_daily, "#{@default_day}",  class: "form-control", "data-format" => "yyyy-MM-dd", style: "width: 120px;" 
    %span{ class: "add-on" }
      %i{class: "icon-th"}
  = button_tag :show, class: "btn btn-primary", id: "apply_daily"    

app/views/admin/latency_statistics/_date_day_hourly.html.haml
.form-group
  #datepicker_day_hourly{class: "input-append date"}
    = text_field_tag :date_day_hourly, "#{@default_day}",  class: "form-control", "data-format" => "yyyy-MM-dd", style: "width: 120px;" 
    %span{ class: "add-on" }
      %i{class: "icon-th"}
  = button_tag :show, class: "btn btn-primary", id: "apply_day_hourly"    

app/views/admin/latency_statistics/_date_hourly.html.haml
.form-group
  #datepicker_hourly{class: "input-append date"}
    = text_field_tag :date_hourly, "#{ @default_hour_day }",  class: "form-control", "data-format" => "yyyy-MM-dd", style: "width: 120px;" 
    %span{ class: "add-on" }
      %i{class: "icon-th"}
  %div
    Hour:    
    = select_tag :hour, options_for_select( (0..23).to_a.map{|h| h.to_s.rjust(2, '0')} , @default_hour.to_s.rjust(2, '0')) , style: "width: 60px;"
  = button_tag :show, class: "btn btn-primary", id: "apply_hourly"    

app/views/admin/latency_statistics/_date_monthly.html.haml
.form-group
  #datepicker_monthly{class: "input-append date"}
    = text_field_tag :date_monthly, "#{@default_month}",  class: "form-control",  style: "width: 120px;" 
    %span{ class: "add-on" }
      %i{class: "icon-th"}
  = button_tag :show, class: "btn btn-primary", id: "apply_monthly"    

app/views/admin/latency_statistics/_lineal_charts.html.haml
.row-fluid.total.day_hourly
  .span2
    = render partial: "date_day_hourly"
  .span10.text-center{id: "total", style: "height: 500px;"}

  #by_sources.span10.pull-right
    

app/views/admin/latency_statistics/index.html.haml
:javascript

  window.config = {
      update_latency_path : "#{admin_update_latency_offset_path }",
      latency_offset: "#{@latency_offset}",

      min_day: "#{ @min_day }",
      max_day: "#{ @max_day }",
      default_day: "#{ @default_day }",

      min_month: "#{ @min_month }",
      max_month: "#{ @max_month }",
      default_month: "#{ @default_month }",

      periods: ["hourly", "daily", "monthly"],
      urls: {
          "hourly": "#{admin_latency_hourly_path}",
          "daily": "#{admin_latency_daily_path}",
          "monthly": "#{admin_latency_monthly_path}",
          "day_hourly": "#{admin_latency_day_hourly_path}" 
      }
  }; 

= javascript_include_tag "highcharts", "chartkick", "admin/latency_statistic"
.container
  %h3 Average latency Statistics
  .row-fluid.total.text-right
    = render 'change_offset' 
  .row-fluid.total
    %ul.nav.nav-tabs
      %li.active
        %a{ "href" => "#latency_hourly", "data-target" => "#latency_hourly", "data-toggle" => "tab" }
          Hourly
      %li
        %a{ "href" => "#latency_daily", "data-target" => "#latency_daily", "data-toggle" => "tab" }
          Daily
      %li
        %a{ "href" => "#latency_monthly", "data-target" => "#latency_monthly", "data-toggle" => "tab" }
          Monthly
      %li
        %a{ "href" => "#latency_lineal", "data-target" => "#latency_lineal", "data-toggle" => "tab" }
          Lineal        
  .tab-content      
    - @series.each do |title, latencies| 
      - if title.to_s == "hourly" 
        .tab-pane.active{id: "latency_#{title}"}
          = render partial: "chart", locals: { latencies: latencies, title: title }
      - else        
        .tab-pane{id: "latency_#{title}"}
          = render partial: "chart", locals: { latencies: latencies, title: title } 
    .tab-pane{id: "latency_lineal"}
      = render partial: "lineal_charts"    