config/routes.rb
require 'sidekiq/web'

ThreetapsPostingApi::Application.routes.draw do
  mount Sidekiq::Web, at: "/admin/sidekiq"

  get '/proxy' =>  'proxies#proxy'
  post '/proxy' =>  'proxies#proxy'

  get "/login" => "clients#login"
  post "/login" => "clients#authenticate"
  get '/logout' => "clients#logout"

  get "request_builders/locations" => "request_builders#locations"
  get "request_builders/polling" => "request_builders#polling"
  get "request_builders/reference_api_request" => "request_builders#reference_api_request"

  get "report_data" => "source_category_statistics#index"
  post 'stats' => 'stats#create'

  get '/sources/zip_stats(.:format)' => "zips#old_date_zips"

  get "annotations" => "annotations#index"
  get "available_annotations" => 'annotations_locations#index'
  get 'bckpg_process' => "bckpgs#bckpg_process"
  root 'postings#create', via: :post
  get '/' => 'payment_home#index'
  get 'anchor' => 'postings#anchor'
  get 'anchor2' => 'postings#anchor2'
  get 'poll' => 'postings#poll'
  get 'postings/:id' => 'postings#show'
  get 'pages/health' => 'pages#health'
  scope 'html-postings' do
    post 'craig' => 'html_postings#craig'
  end

  post '/scrapers/info' => 'scraper_infos#create'

  #match 'post_single', to: 'postings#options', via: [:options], constraints: {method: 'OPTIONS'}
  match 'post_single', to: 'postings#create', via: [:post, :options]
  #post 'post_single' => 'postings#create'
  #match 'post_multi', to: 'postings#create', via: [:post, :options]
  post 'post_multi' => 'postings#create'
  post 'post_raw_single' => 'postings#raw_create'
  post 'post_raw_multi' => 'postings#raw_create'

  get "/payment_home" => 'payment_home#index'
  get '/contracts' => 'payment_home#contracts'
  get "/contracts_rates" => 'payment_home#client_rates'
  get "/category_group/:category_group" => 'payment_home#categories', as: :category_group

  resources :demand_source_rates, only: [:index, :edit, :update, :create]

  resources :posting_examples, only: [:new, :create]
  resources :html_examples, only: [:new, :create]
  #get 'admin' => 'admin#index'
  namespace :admin do
    get "posting_stats" => 'posting_stats#index'
    get "insert_profilers" => 'insert_profilers#index'
    get "system_events" => 'system_events#index'
    get "system_events/show" => 'system_events#show'
    get '/' => 'home#index'
    put '/' => 'home#update'

    get '/accounts/refresh' => 'accounts#refresh_approved', as: 'refresh_approved_accounts'

    resources :annotations do
      collection do
        get 'csv' => 'annotations#csv_export', as: 'csv'
      end
    end

    resources :calculate_annotations, only: [ :index ] do
      collection do
        put '/' => 'calculate_annotations#update'
      end
    end

    resources :quality_statistics, only: [ :index ] do
      collection do
        get '/incomplete_annotations' => 'quality_statistics#incomplete_annotations', as: 'incomplete_annotations'
        get '/incomplete_fields' => 'quality_statistics#incomplete_fields', as: 'incomplete_fields'
        match '/with_:attribute' => 'quality_statistics#postings_with_quality', via: [ :get ], constraints: { attribute: /(fields|annotations)_quality/ }, as: 'postings_with_quality'
      end
    end

    get "/annotations_qualities" => 'quality_statistics#annotations_qualities'
    get "/fields_qualities" => 'quality_statistics#fields_qualities'

    resources :converters
    resources :response_counts

    resources :proxy_ips, only: :index

    resources :statistics, only: [ :index ] do
      collection do
        get '/live_data' => 'statistics#live_data', as: 'live_data'
        get '/total_data' => 'statistics#total_data', as: 'total_data'
        get '/us_borders(.:format)' => 'statistics#us_borders'
        get '/states_data(.:format)' => 'statistics#states_data'
        get '/antengo' => 'statistics#antengo', as: 'antengo'
      end

    end

    resources :empty_timestamps, only: [ :index ]
    get "/empty_ids" => "empty_timestamps#show_ids"

    get '/live_lovely' => "live_lovelies#index", as: :live_lovelies

    resources :payment_rates, only: [ :index, :edit, :update ]
    post 'update_categories_rates' => 'payment_rates#update_categories_rates'

    resources :payment_reports, only: :index

    resources :source_accounts, only: :index

    resources :latency_statistics, only: :index

    post "update_latency_offset" => "latency_statistics#update_latency_offset"

    get "latency_hourly" => "latency_statistics#latency_hourly"
    get "latency_daily" => "latency_statistics#latency_daily"
    get "latency_monthly" => "latency_statistics#latency_monthly"
    get "latency_day_hourly" => "latency_statistics#latency_day_hourly"

    get "update_sources" => "backpage_sources#update_sources"
    get "update_file" => "backpage_sources#update_file"
    get "filter_by_address" => "response_counts#filter_by_address"
    get "filter_by_date" => "response_counts#filter_by_date"
    resources :sources, only: :index do
      collection do
        get ":source" => "sources#zips_by_source", as: 'zips_by_source'
        get "/carmakers/:source" => "sources#carmakers_by_source", as: 'carmakers_by_source'
      end
    end

    resources :notifications, only: [:index, :update]
    resources :html_examples, path: 'html-examples', only: [:index, :show] do
      member do
        delete '/' => 'html_examples#reject'
        post '/' => 'html_examples#accept'
        put '/' => 'html_examples#ready'
      end
    end
    scope 'compliances', as: :compliances do
      get '/' => 'compliances#index'
      post '/' => 'compliances#index'
    end

    scope 'parsing', as: :parsing do
      get '/' => 'parsing#index'
      get '/:source' => 'parsing#show', as: :show
      get '/mockup' => 'parsing#show' #trick!?
      post '/' => 'parsing#create'
    end

    resources :exceptions, only: :index do
      # get '/' => 'exceptions#index'
      member do
        get 'retry_last_posting'
        get 'retry_all_postings'
        get 'delete'
        get 'details', as: :details
      end
    end

    resources :auth_tokens

    get '/token_settings/:id' => "auth_tokens#settings", as: :token_settings
    get '/generate_token' => "auth_tokens#generate_token", as: :generate_token

    get '/scrapers/info' => "scraper_infos#index", as: :scraper_infos
    # resources :scraper_infos, only: :index

    scope 'partitions', as: :partitions do
      get '/' => 'partitions#index'
      post '/' => 'partitions#index'
    end
  end
end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  QUEUE_NAME = 'posting_annotations'
  PROCESSING_ENABLED = false

  CONTROL_TYPES = %w(text select multiselect checkbox range)
  OVERRIDE_VALUES = { 'yes' => true, 'no' => false }
  ALLOWED_OPTIONS = %w(status phone price bedrooms sqft cats dogs make model vin year age personal_flavor compensation part_time telecommute contract internship nonprofit)

  serialize :sources, Array
  serialize :categories, Array
  serialize :category_groups, Array
  serialize :options, Array
  serialize :public_options, Array

  validates :control_type, :inclusion => { :in => CONTROL_TYPES }

  def public?
    self.is_public || true
  end

  def sent_as_annotation?
    self.sent_as_annotation
  end

  def renderable_options
    if self.public_options.present?
      self.public_options
    else
      self.options
    end
  end

  def all_sources?
    if self.override_all_sources_value.present?
      self.override_all_sources_value
    else
      self.sources.sort.map(&:to_s) == PostingConstants::SOURCES.sort.map(&:to_s)
    end
  end

  def all_categories?
    if self.override_all_categories_value.present?
      self.override_all_categories_value
    else
      self.categories.sort.map(&:to_s) == PostingConstants::CATEGORIES.sort.map(&:to_s)
    end
  end

  def all_category_groups?
    if self.override_all_category_groups_value.present?
      self.override_all_category_groups_value
    else
      self.category_groups && (self.category_groups.sort.map(&:to_s) == PostingConstants::CATEGORY_GROUPS.sort.map(&:to_s))
    end
  end

  def all_categories_in_group?
    if self.override_all_categories_in_group_value.present?
      self.override_all_categories_in_group_value
    else
      # TODO: rework
      false
    end
  end
end

app/controllers/admin/annotations_controller.rb
class Admin::AnnotationsController < Admin::ApplicationController
  
  def index
    @annotations = Annotation.all
    add_breadcrumb "index", admin_annotations_path
  end

  def new
    @annotation = Annotation.new
    add_breadcrumb "New"
  end

  def edit
    @annotation = Annotation.find params[:id]
    add_breadcrumb "Edit"
  end

  def create
    @annotation = Annotation.new(annotation_params)

    if @annotation.save
      redirect_to admin_annotations_path
    else
      render :new
    end
  end

  def update
    @annotation = Annotation.find params[:id]

    if @annotation.update_attributes annotation_params
      redirect_to admin_annotations_path
    else
      render :edit
    end
  end

  def csv_export
    annotations = Annotation.all

    data = CSV.generate do |csv|
      csv << [ 'name', 'sources', 'categories', 'control type', 'is public' ]

      annotations.each do |annotation|
        csv << [
          annotation.name,
          annotation.sources.join('|'),
          annotation.categories.join('|'),
          annotation.control_type,
          annotation.public?
        ]
      end
    end

    filename = "annotations.#{ DateTime.now.strftime('%H-%M.%d-%m-%Y') }.csv"

    send_data data, :type => 'text/csv; charset=utf-8; header=present', :filename => filename
  end

  private

  def annotation_params
    params.require(:annotation).permit!

    params[:annotation][:sources].reject! { |source| source.blank? }

    params[:annotation]
  end
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  include ApplicationHelper

  after_filter :cors_set_access_control_headers

  def index
    render json: { errors: ["auth_token is absent"] }.to_json and return unless params[:auth_token].present?

    filter_annotations

    render json: annotations_response_format.to_json
  end

  protected

  def filter_by(filter_key, &block)
    return if @filters[filter_key].blank?

    @annotations.select! do |annotation|
      if block_given?
        block.call(annotation)
      else
        not (annotation[filter_key] & @filters[filter_key].split(',')).empty?
      end
    end
  end

  def annotations_response_format
    results = @annotations.map do |annotation|
      next unless annotation.public?

      result = {
          name: annotation.name,
          sources: annotation.sources,
          categories: annotation.categories,
          category_groups: annotation.category_groups,
          control_type: annotation.control_type,
          sent_as_annotation: annotation.sent_as_annotation?,
          options: annotation.renderable_options
      }

      result[:all_sources] = annotation.all_sources? if annotation.all_sources?
      result[:all_categories] = annotation.all_categories? if annotation.all_categories?
      result[:all_category_groups] = annotation.all_category_groups? if annotation.all_category_groups?
      result[:all_categories_in_group] = annotation.all_categories_in_group? if annotation.all_categories_in_group?

      result
    end

    results.compact
  end

  def filter_annotations
    @annotations = Annotation.all.to_a
    @filters = params.dup

    filter_by(:sources)
    filter_by(:category_groups)
    filter_by(:categories)
  end

end

app/views/admin/annotations/_form.html.haml
:scss
  .margined, .margined > div
  {
    margin-bottom: 5px;
  }

:javascript
  $(document).ready(function(){
    $('body').on('click', '.remove_value', function(e) {
      $(this).parent().remove();
      e.preventDefault();
    });

    $('#add-option').click(function(e) {
      var field_name = "annotation[options][]";
      var html = "<div class='span6'><input type='text' name='annotation[options][][name]' /> <input type='checkbox' name='annotation[options][][public]' value='1' /> <span> public</span> <span class='btn btn-small btn-danger remove_value'>Remove</span></div><br />";

      $("#options").append(html);
      e.preventDefault();
    });
  });

.row
  .control-group
    = f.label :name, :class => 'control-label'

    .controls
      = f.text_field :name

.row
  .control-group
    = f.label :categories, :class => 'control-label'

    .controls
      = f.select :categories, PostingConstants::CATEGORIES, { include_blank: false }, { multiple: true }

.row
  .control-group
    = f.label :control_type, :class => 'control-label'

    .controls
      = f.select :control_type, Annotation::CONTROL_TYPES

.row
  .control-group
    = f.label :is_public, :class => 'control-label'

    .controls
      = f.check_box :is_public

.row
  .control-group
    = f.label :sources, :class => 'control-label'

    .controls
      = f.select :sources, PostingConstants::SOURCES, { include_blank: false }, { multiple: true }

.row
  .control-group
    = f.label :options, :class => 'control-label'

    .controls
      %span#add-option.margined.btn.btn-small.btn-primary
        Add option

      .row.margined#options
        - if @annotation[:options].present?
          - @annotation[:options].each do |option|
            .span6
              = text_field_tag "annotation[options][][name]", option['name']
              = check_box_tag "annotation[options][][public]", "1", option['public']

              %span
                public

              %span.btn.btn-small.btn-danger.remove_value
                Remove

.row
  .control-group
    = f.label :override_all_sources_value, :class => 'control-label'

    .controls
      = f.select :override_all_sources_value, Annotation::OVERRIDE_VALUES, { include_blank: "- autodetect -" }, { multiple: false }

.row
  .control-group
    = f.label :override_all_category_groups_value, :class => 'control-label'

    .controls
      = f.select :override_all_category_groups_value, Annotation::OVERRIDE_VALUES, { include_blank: "- autodetect -" }, { multiple: false }

.row
  .control-group
    = f.label :override_all_categories_value, :class => 'control-label'

    .controls
      = f.select :override_all_categories_value, Annotation::OVERRIDE_VALUES, { include_blank: "- autodetect -" }, { multiple: false }

.row
  .control-group
    = f.label :override_all_categories_in_group_value, :class => 'control-label'

    .controls
      = f.select :override_all_categories_in_group_value, Annotation::OVERRIDE_VALUES, { include_blank: "- autodetect -" }, { multiple: false }

.row
  .span5.text-center
    - submit_title = (action_name == 'edit') ? 'Update' : 'Create'
    = f.submit submit_title, class: 'btn btn-large btn-primary'

app/views/admin/annotations/edit.html.haml
.container
  %h3 Edit annotation

  .container
    = form_for([:admin, @annotation], html: { role: "form", class: 'form-horizontal' }) do |f|
      = render 'form', f: f

app/views/admin/annotations/index.haml
:javascript
  $(document).ready(function() {
    function filterByCategory() {
      var categories = $('.category_filter:checked').map(function(idx, elt) { return $(elt).val() });

      $('tbody tr').show();

      if (categories.length < 1) {
        return;
      }

      $('tbody td.categories').each(function(idx, elt) {
        categories.each(function(idx, category) {
          if (!$(elt).text().contains(category)) {
            $(elt).parent('tr').hide();
            return false;
          }
        });
      });
    }

    $(".table").tablesorter({ theme: 'blue', sortReset: true });

    $('.search').val('');

    $('.search').on('keyup', function() {
      var query = $(this).val(),
          pattern = new RegExp('^' + query, 'i');

      if (query.trim().length < 1) {
        $('tr').has('.filter_field').show()
        return;
      }

      $('.filter_field').each(function(idx, item) {
        var field = $(item).text().trim(),
            row = $(item).parents('tr');

        if (!pattern.test(field)) {
          row.hide();
        } else {
          row.show();
        }
      });
    });

    $('.category_filter').each(function(idx, elt) {
      $(elt).prop('checked', true);
    });

    $('.category_filter_all').click(function() {
      $('.category_filter').each(function(idx, elt) {
        $(elt).prop('checked', true);
      });

      filterByCategory();
    });

    $('.category_filter_none').click(function() {
      $('.category_filter').each(function(idx, elt) {
        $(elt).prop('checked', false);
      });

      filterByCategory();
    });

    $('.category_filter').on('change', function() {
      filterByCategory();
    });
  });

:css
  .table thead tr {
    background-color: #bedebe;
  }

.container
  %h3 Annotations

  .row
    .span12
      = link_to "Add annotation", new_admin_annotation_path, class: "btn btn-middle btn-primary"
      = link_to "Export to CSV", csv_admin_annotations_path, class: "btn btn-middle btn-primary"

  .row
    .span12
      &nbsp;

  - if not @annotations.present?
    .alert.alert-info
      No annotations found
  - else
    .row
      .span12
        %input.search{ :placeholder => "Filter by name" }

    .row
      .span12
        &nbsp;

    .row
      .span12
        .accordion#accordion1
          .accordion-group
            .accordion-heading
              %a.accordion-toggle{ 'data-toggle' => "collapse", 'data-parent' => "#accordion1", 'href' => "#collapse1" }
                Category filter

            #collapse1.accordion-body.collapse
              .accordion-inner
                .row
                  .span12
                    %a.category_filter_all.btn.btn-middle.btn-primary
                      All

                    %a.category_filter_none.btn.btn-middle.btn-primary
                      None

                .row
                  - PostingConstants::CATEGORIES.in_groups(4).each do |group|
                    .span2
                      - group.each do |category|
                        - next if category.blank?

                        %label.checkbox
                          = category
                          %input.category_filter{ :type => 'checkbox', :value => category }

    .row
      .span12
        %table.table.table-bordered.list
          %thead
            %tr
              %th Annotation
              %th Sources
              %th Category
              %th Control type
              %th Is public
              %th Actions

          %tbody
            - @annotations.each do |annotation|
              %tr
                %td.filter_field
                  = annotation.name

                %td
                  = annotation.sources.join ','

                %td.categories
                  = annotation.categories.join ','

                %td
                  = annotation.control_type

                %td
                  = annotation.public?

                %td
                  = link_to 'Edit', edit_admin_annotation_path(annotation), class: 'btn btn-small btn-primary'

app/views/admin/annotations/new.html.haml
.container
  %h3 New annotation

  .container
    = form_for(@annotation, url: admin_annotations_path, html: { role: "form", class: 'form-horizontal' }) do |f|
      = render 'form', f: f