config/routes.rb
require 'sidekiq/web'

ThreetapsPostingApi::Application.routes.draw do
  mount Sidekiq::Web, at: "/admin/sidekiq"

  get '/proxy' =>  'proxies#proxy'
  post '/proxy' =>  'proxies#proxy'

  get "/login" => "clients#login"
  post "/login" => "clients#authenticate"
  get '/logout' => "clients#logout"

  get "request_builders/locations" => "request_builders#locations"
  get "request_builders/polling" => "request_builders#polling"
  get "request_builders/reference_api_request" => "request_builders#reference_api_request"

  get "report_data" => "source_category_statistics#index"
  post 'stats' => 'stats#create'

  get '/sources/zip_stats(.:format)' => "zips#old_date_zips"

  get "annotations" => "annotations#index"
  get "available_annotations" => 'annotations_locations#index'
  get 'bckpg_process' => "bckpgs#bckpg_process"
  root 'postings#create', via: :post
  get '/' => 'payment_home#index'
  get 'anchor' => 'postings#anchor'
  get 'anchor2' => 'postings#anchor2'
  get 'poll' => 'postings#poll'
  get 'postings/:id' => 'postings#show'
  get 'pages/health' => 'pages#health'
  scope 'html-postings' do
    post 'craig' => 'html_postings#craig'
  end

  post '/scrapers/info' => 'scraper_infos#create'

  #match 'post_single', to: 'postings#options', via: [:options], constraints: {method: 'OPTIONS'}
  match 'post_single', to: 'postings#create', via: [:post, :options]
  #post 'post_single' => 'postings#create'
  #match 'post_multi', to: 'postings#create', via: [:post, :options]
  post 'post_multi' => 'postings#create'
  post 'post_raw_single' => 'postings#raw_create'
  post 'post_raw_multi' => 'postings#raw_create'

  get "/payment_home" => 'payment_home#index'
  get '/contracts' => 'payment_home#contracts'
  get "/contracts_rates" => 'payment_home#client_rates'
  get "/category_group/:category_group" => 'payment_home#categories', as: :category_group

  resources :demand_source_rates, only: [:index, :edit, :update, :create]

  resources :posting_examples, only: [:new, :create]
  resources :html_examples, only: [:new, :create]
  #get 'admin' => 'admin#index'
  namespace :admin do
    get "posting_stats" => 'posting_stats#index'
    get "insert_profilers" => 'insert_profilers#index'
    get "system_events" => 'system_events#index'
    get "system_events/show" => 'system_events#show'
    get '/' => 'home#index'
    put '/' => 'home#update'

    get '/accounts/refresh' => 'accounts#refresh_approved', as: 'refresh_approved_accounts'

    resources :annotations do
      collection do
        get 'csv' => 'annotations#csv_export', as: 'csv'
      end
    end

    resources :calculate_annotations, only: [ :index ] do
      collection do
        put '/' => 'calculate_annotations#update'
      end
    end

    resources :quality_statistics, only: [ :index ] do
      collection do
        get '/incomplete_annotations' => 'quality_statistics#incomplete_annotations', as: 'incomplete_annotations'
        get '/incomplete_fields' => 'quality_statistics#incomplete_fields', as: 'incomplete_fields'
        match '/with_:attribute' => 'quality_statistics#postings_with_quality', via: [ :get ], constraints: { attribute: /(fields|annotations)_quality/ }, as: 'postings_with_quality'
      end
    end

    get "/annotations_qualities" => 'quality_statistics#annotations_qualities'
    get "/fields_qualities" => 'quality_statistics#fields_qualities'

    resources :converters
    resources :response_counts

    resources :proxy_ips, only: :index

    resources :statistics, only: [ :index ] do
      collection do
        get '/live_data' => 'statistics#live_data', as: 'live_data'
        get '/total_data' => 'statistics#total_data', as: 'total_data'
        get '/us_borders(.:format)' => 'statistics#us_borders'
        get '/states_data(.:format)' => 'statistics#states_data'
        get '/antengo' => 'statistics#antengo', as: 'antengo'
      end

    end

    resources :empty_timestamps, only: [ :index ]
    get "/empty_ids" => "empty_timestamps#show_ids"

    get '/live_lovely' => "live_lovelies#index", as: :live_lovelies

    resources :payment_rates, only: [ :index, :edit, :update ]
    post 'update_categories_rates' => 'payment_rates#update_categories_rates'

    resources :payment_reports, only: :index

    resources :source_accounts, only: :index

    resources :latency_statistics, only: :index

    post "update_latency_offset" => "latency_statistics#update_latency_offset"

    get "latency_hourly" => "latency_statistics#latency_hourly"
    get "latency_daily" => "latency_statistics#latency_daily"
    get "latency_monthly" => "latency_statistics#latency_monthly"
    get "latency_day_hourly" => "latency_statistics#latency_day_hourly"

    get "update_sources" => "backpage_sources#update_sources"
    get "update_file" => "backpage_sources#update_file"
    get "filter_by_address" => "response_counts#filter_by_address"
    get "filter_by_date" => "response_counts#filter_by_date"
    resources :sources, only: :index do
      collection do
        get ":source" => "sources#zips_by_source", as: 'zips_by_source'
        get "/carmakers/:source" => "sources#carmakers_by_source", as: 'carmakers_by_source'
      end
    end

    resources :notifications, only: [:index, :update]
    resources :html_examples, path: 'html-examples', only: [:index, :show] do
      member do
        delete '/' => 'html_examples#reject'
        post '/' => 'html_examples#accept'
        put '/' => 'html_examples#ready'
      end
    end
    scope 'compliances', as: :compliances do
      get '/' => 'compliances#index'
      post '/' => 'compliances#index'
    end

    scope 'parsing', as: :parsing do
      get '/' => 'parsing#index'
      get '/:source' => 'parsing#show', as: :show
      get '/mockup' => 'parsing#show' #trick!?
      post '/' => 'parsing#create'
    end

    resources :exceptions, only: :index do
      # get '/' => 'exceptions#index'
      member do
        get 'retry_last_posting'
        get 'retry_all_postings'
        get 'delete'
        get 'details', as: :details
      end
    end

    resources :auth_tokens

    get '/token_settings/:id' => "auth_tokens#settings", as: :token_settings
    get '/generate_token' => "auth_tokens#generate_token", as: :generate_token

    get '/scrapers/info' => "scraper_infos#index", as: :scraper_infos
    # resources :scraper_infos, only: :index

    scope 'partitions', as: :partitions do
      get '/' => 'partitions#index'
      post '/' => 'partitions#index'
    end
  end
end

app/controllers/admin/sources_controller.rb
class Admin::SourcesController < Admin::ApplicationController
  DEFAULT_LIMIT = 24

  before_action :init_limit, only: :index

  def index
    @track_carmakers = PostingConstants::TRACK_CARMAKER_SOURCES

    @sources = Posting2.recent_postings_by_source
    
    add_breadcrumb :sources, :admin_sources_path
  end

  def zips_by_source
    @time = Time.now
    
    @source = source_params[:source]
    zips = ZipsTracker.get_zips(@source)
    
    @present_zips = zips[:present]
    @missing_zips = zips[:missing]
    
    add_breadcrumb "Sources", :admin_sources_path
    add_breadcrumb "Last date by zips"
  end  

  def carmakers_by_source
    @source = source_params[:source]
    
    if PostingConstants::TRACK_CARMAKER_SOURCES.include?(@source)    
      @time = Time.now
      
      carmakers = Carmaker.get_data(@source)
      
      @present_carmakers = carmakers[:present]
      @missing_carmakers = carmakers[:missing]
      
      add_breadcrumb "Sources", :admin_sources_path
      add_breadcrumb "Carmakers"
    else
      redirect_to action: :index
    end
  end  

  private

  def init_limit
    @limit = (params[:hours] || DEFAULT_LIMIT).to_i.hours.ago
  end

  def source_params
    params.permit(:source)
  end  
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/admin/sources/carmakers_by_source.html.haml
:javascript
  $(function() {
    $('#hours-slider').slider({
      value: #{params[:hours] || 1},
      min: 1,
      max: 7 * 24
    }).on('slide', function(evt) {
      updateColors();
    });

    updateColors();
    updateCurrentTime();

    setInterval(updateCurrentTime, 1000);
  });

.container
  %h4
    Last date for Carmakers for source
    = @sourse

  %div
    %strong
      Time now:
      %span#current_time

  .row
    .span12
      &nbsp;

  .row
    .span6.text-right
      Hours ago:

    .span6
      #hours-slider

  .row
    .span12
      &nbsp;

  %ul.nav.nav-tabs
    %li.active
      %a{ "href" => "#present_carmakers", "data-target" => "#present_carmakers", "data-toggle" => "tab" }
        Present

    %li
      %a{ "href" => "#missing_carmakers", "data-target" => "#missing_carmakers", "data-toggle" => "tab" }
        Missing

  .tab-content
    #present_carmakers.tab-pane.active
      %strong
        Total: #{ @present_carmakers ? @present_carmakers.size : 0 }

      %ul
        - @present_carmakers.each do |carmaker, date|
          %li
            %strong
              = carmaker

            %span.color-plate{ 'data-timestamp' => date }
              = "#{ time_ago_in_words(date) } ago (#{ date })"

    #missing_carmakers.tab-pane
      %strong
        Total: #{  @missing_carmakers ? @missing_carmakers.size : 0}

      %ul
        - @missing_carmakers.each do |carmaker|
          %li
            = carmaker

app/views/admin/sources/index.html.haml
:javascript
  $(function() {
    $('#hours-slider').slider({
      value: #{params[:hours] || 1},
      min: 1,
      max: 7 * 24
    }).on('slide', function(evt) {
      updateColors();
    });

    updateColors();
    updateCurrentTime();

    setInterval(updateCurrentTime, 1000);
  });
:css
  h3 {  line-height: 25px;}    

.row
  .span12.text-center
    %strong Current time:
    %span#current_time

.row
  .span12
    &nbsp;

.row
  .span6.text-right
    Hours ago:

  .span6
    #hours-slider

.row
  .span12
    &nbsp;

- @sources.in_groups_of(4) do |group|
  .row
    - group.each do |source|
      - next if source.nil?

      - present source, SourcePresenter do |p|
        .span3.text-center.color-plate{ 'data-timestamp' => p.timestamp }
          %h3
            = link_to p.name, zips_by_source_admin_sources_path(p.name), style: "color: #5e5e5e"
          - if @track_carmakers.include?(p.name)  
            = link_to :carmakers, carmakers_by_source_admin_sources_path(p.name), style: "color: #5e5e5e"
          - else
            %br   
          %p.relative-time
            #{ time_ago_in_words(p.timestamp) } ago

          %p
            = p.timestamp.strftime('%D %T UTC')

  .row
    .span12
      &nbsp;

app/views/admin/sources/zips_by_source.html.haml
:javascript
  $(function() {
    $('#hours-slider').slider({
      value: #{params[:hours] || 1},
      min: 1,
      max: 7 * 24
    }).on('slide', function(evt) {
      updateColors();
    });

    updateColors();
    updateCurrentTime();

    setInterval(updateCurrentTime, 1000);
  });

.container
  %h4
    Last date for ZIPs for source
    = @sourse

  %div
    %strong
      Time now:
      %span#current_time

  .row
    .span12
      &nbsp;

  .row
    .span6.text-right
      Hours ago:

    .span6
      #hours-slider

  .row
    .span12
      &nbsp;

  %ul.nav.nav-tabs
    %li.active
      %a{ "href" => "#zips_present", "data-target" => "#zips_present", "data-toggle" => "tab" }
        Present

    %li
      %a{ "href" => "#zips_missing", "data-target" => "#zips_missing", "data-toggle" => "tab" }
        Missing

  .tab-content
    #zips_present.tab-pane.active
      %strong
        Total: #{ @present_zips.size }

      %ul
        - @present_zips.each do |zip, date|
          %li
            %strong
              = zip

            %span.color-plate{ 'data-timestamp' => date }
              = "#{ time_ago_in_words(date) } ago (#{ date })"

    #zips_missing.tab-pane
      %strong
        Total: #{ @missing_zips.size }

      %ul
        - @missing_zips.each do |zip|
          %li
            = zip