config/routes.rb
require 'sidekiq/web'

ThreetapsPostingApi::Application.routes.draw do
  mount Sidekiq::Web, at: "/admin/sidekiq"

  get '/proxy' =>  'proxies#proxy'
  post '/proxy' =>  'proxies#proxy'

  get "/login" => "clients#login"
  post "/login" => "clients#authenticate"
  get '/logout' => "clients#logout"

  get "request_builders/locations" => "request_builders#locations"
  get "request_builders/polling" => "request_builders#polling"
  get "request_builders/reference_api_request" => "request_builders#reference_api_request"

  get "report_data" => "source_category_statistics#index"
  post 'stats' => 'stats#create'

  get '/sources/zip_stats(.:format)' => "zips#old_date_zips"

  get "annotations" => "annotations#index"
  get "available_annotations" => 'annotations_locations#index'
  get 'bckpg_process' => "bckpgs#bckpg_process"
  root 'postings#create', via: :post
  get '/' => 'payment_home#index'
  get 'anchor' => 'postings#anchor'
  get 'anchor2' => 'postings#anchor2'
  get 'poll' => 'postings#poll'
  get 'postings/:id' => 'postings#show'
  get 'pages/health' => 'pages#health'
  scope 'html-postings' do
    post 'craig' => 'html_postings#craig'
  end

  post '/scrapers/info' => 'scraper_infos#create'

  #match 'post_single', to: 'postings#options', via: [:options], constraints: {method: 'OPTIONS'}
  match 'post_single', to: 'postings#create', via: [:post, :options]
  #post 'post_single' => 'postings#create'
  #match 'post_multi', to: 'postings#create', via: [:post, :options]
  post 'post_multi' => 'postings#create'
  post 'post_raw_single' => 'postings#raw_create'
  post 'post_raw_multi' => 'postings#raw_create'

  get "/payment_home" => 'payment_home#index'
  get '/contracts' => 'payment_home#contracts'
  get "/contracts_rates" => 'payment_home#client_rates'
  get "/category_group/:category_group" => 'payment_home#categories', as: :category_group

  resources :demand_source_rates, only: [:index, :edit, :update, :create]

  resources :posting_examples, only: [:new, :create]
  resources :html_examples, only: [:new, :create]
  #get 'admin' => 'admin#index'
  namespace :admin do
    get "posting_stats" => 'posting_stats#index'
    get "insert_profilers" => 'insert_profilers#index'
    get "system_events" => 'system_events#index'
    get "system_events/show" => 'system_events#show'
    get '/' => 'home#index'
    put '/' => 'home#update'

    get '/accounts/refresh' => 'accounts#refresh_approved', as: 'refresh_approved_accounts'

    resources :annotations do
      collection do
        get 'csv' => 'annotations#csv_export', as: 'csv'
      end
    end

    resources :calculate_annotations, only: [ :index ] do
      collection do
        put '/' => 'calculate_annotations#update'
      end
    end

    resources :quality_statistics, only: [ :index ] do
      collection do
        get '/incomplete_annotations' => 'quality_statistics#incomplete_annotations', as: 'incomplete_annotations'
        get '/incomplete_fields' => 'quality_statistics#incomplete_fields', as: 'incomplete_fields'
        match '/with_:attribute' => 'quality_statistics#postings_with_quality', via: [ :get ], constraints: { attribute: /(fields|annotations)_quality/ }, as: 'postings_with_quality'
      end
    end

    get "/annotations_qualities" => 'quality_statistics#annotations_qualities'
    get "/fields_qualities" => 'quality_statistics#fields_qualities'

    resources :converters
    resources :response_counts

    resources :proxy_ips, only: :index

    resources :statistics, only: [ :index ] do
      collection do
        get '/live_data' => 'statistics#live_data', as: 'live_data'
        get '/total_data' => 'statistics#total_data', as: 'total_data'
        get '/us_borders(.:format)' => 'statistics#us_borders'
        get '/states_data(.:format)' => 'statistics#states_data'
        get '/antengo' => 'statistics#antengo', as: 'antengo'
      end

    end

    resources :empty_timestamps, only: [ :index ]
    get "/empty_ids" => "empty_timestamps#show_ids"

    get '/live_lovely' => "live_lovelies#index", as: :live_lovelies

    resources :payment_rates, only: [ :index, :edit, :update ]
    post 'update_categories_rates' => 'payment_rates#update_categories_rates'

    resources :payment_reports, only: :index

    resources :source_accounts, only: :index

    resources :latency_statistics, only: :index

    post "update_latency_offset" => "latency_statistics#update_latency_offset"

    get "latency_hourly" => "latency_statistics#latency_hourly"
    get "latency_daily" => "latency_statistics#latency_daily"
    get "latency_monthly" => "latency_statistics#latency_monthly"
    get "latency_day_hourly" => "latency_statistics#latency_day_hourly"

    get "update_sources" => "backpage_sources#update_sources"
    get "update_file" => "backpage_sources#update_file"
    get "filter_by_address" => "response_counts#filter_by_address"
    get "filter_by_date" => "response_counts#filter_by_date"
    resources :sources, only: :index do
      collection do
        get ":source" => "sources#zips_by_source", as: 'zips_by_source'
        get "/carmakers/:source" => "sources#carmakers_by_source", as: 'carmakers_by_source'
      end
    end

    resources :notifications, only: [:index, :update]
    resources :html_examples, path: 'html-examples', only: [:index, :show] do
      member do
        delete '/' => 'html_examples#reject'
        post '/' => 'html_examples#accept'
        put '/' => 'html_examples#ready'
      end
    end
    scope 'compliances', as: :compliances do
      get '/' => 'compliances#index'
      post '/' => 'compliances#index'
    end

    scope 'parsing', as: :parsing do
      get '/' => 'parsing#index'
      get '/:source' => 'parsing#show', as: :show
      get '/mockup' => 'parsing#show' #trick!?
      post '/' => 'parsing#create'
    end

    resources :exceptions, only: :index do
      # get '/' => 'exceptions#index'
      member do
        get 'retry_last_posting'
        get 'retry_all_postings'
        get 'delete'
        get 'details', as: :details
      end
    end

    resources :auth_tokens

    get '/token_settings/:id' => "auth_tokens#settings", as: :token_settings
    get '/generate_token' => "auth_tokens#generate_token", as: :generate_token

    get '/scrapers/info' => "scraper_infos#index", as: :scraper_infos
    # resources :scraper_infos, only: :index

    scope 'partitions', as: :partitions do
      get '/' => 'partitions#index'
      post '/' => 'partitions#index'
    end
  end
end

app/models/demand_source_rate.rb
class DemandSourceRate < PaymentBase
  has_many :demand_group_rates, dependent: :destroy
  accepts_nested_attributes_for :demand_group_rates

  scope :last_month, -> { where(created_at: (Time.now - 1.month).at_beginning_of_month..Time.now.at_beginning_of_month) }
  scope :this_month, -> { where(created_at: Time.now.at_beginning_of_month..Time.now ) }


  def self.fill(prev_count = 12, this_count = 15)
    DemandSourceRate.delete_all
    current_month = Time.now
    prev_month = current_month - 1.month
    available_groups = StatisticByTransferedData.get_available_groups


    [prev_month, current_month].each do |date|
      if prev_month == date
        n = prev_count
        end_date = date.at_end_of_month
      else
        n = this_count
        end_date = date
      end

      (1..n).each do |_n|

        auth_token = (('a'..'z').to_a + (0..9).to_a).shuffle.take(32).join

        available_groups.keys.shuffle.take(rand(available_groups.keys.size)).each do |source|
          DemandSourceRate.create(
            {
              auth_token: auth_token,
              source: source,
              rate: (rand * 0.01).round(4),
              all_groups: true,
              max_sum: rand(1000),
              direction: :out,
              created_at: date,
              updated_at: date
            }
          )

          (date.at_beginning_of_month.to_date..end_date.to_date).each  do |test_date|
            sample_date = date.at_beginning_of_month
            available_groups[source].each do |group|
              StatisticByTransferedData.create(
                {
                  source: source,
                  category_group: group,
                  auth_token: auth_token,
                  for_date: sample_date.strftime("%Y-%m-%d"),
                  ip: '127.0.0.1',
                  amount: rand(1_000),
                  data_size: rand(1_000_000),
                  direction: :out,
                  created_at:test_date,
                  updated_at: test_date
                }
              )
            end
            sample_date += 1.day
          end
        end
      end
    end
    p "creted 9 samples for #{prev_month} and 15 samples for #{current_month}"
  end

end

app/controllers/demand_source_rates_controller.rb
class DemandSourceRatesController < ApplicationController
  layout 'payments'

  before_action :check_client
  before_action :set_params, only: [:index, :edit]
  before_action :verify_authenticity_token, only: :update_rates

  def index
    @source_rates = {}

    @available_groups = session[:available_groups] || StatisticByTransferedData.get_available_groups
    session[:available_groups] = @available_groups

    @available_groups.keys.each do |source|
      @source_rates[source] =  DemandSourceRate.find_by(auth_token: @client.auth_token,  direction: @direction, source: source)

      unless @source_rates[source]
        @source_rates[source] =  DemandSourceRate.create(auth_token: @client.auth_token,  direction: @direction, source: source, all_groups: (source == "CRAIG"))
      end
    end

    # add_breadcrumb "Demand Rates"
  end

  def edit
    @source_rate = DemandSourceRate.find(params[:id])

    if @source_rate.source == "CRAIG" &&  @source_rate.demand_group_rates.empty?
      @available_groups = session[:available_groups] || StatisticByTransferedData.get_available_groups
      @available_groups[@source_rate.source].each do |group|
        @source_rate.demand_group_rates.create(group: group)
      end
    end


    # add_breadcrumb "Demand rates", demand_source_rates_path
    # add_breadcrumb "Edit rate"
  end

  def update
    row = DemandSourceRate.find(params[:id])
    row.update_attributes(demand_params)

    redirect_to demand_source_rates_path
  end

  private

  def check_client
    if session[:client].blank?
      redirect_to login_path and return
    end

    @client = session[:client]
  end

  def set_params
    @direction = params[:direction] || session[:direction] || :out
    session[:direction] = @direction

    @source = params[:source] || "CRAIG"

    @sources = PostingConstants::SOURCES_NAMES
    @groups = PostingConstants::CATEGORY_GROUPS_NAMES
  end

  def demand_params
    params.require(:demand_source_rate).permit(:max_sum, :rate, :all_groups).tap do |whitelisted|
      if params[:demand_source_rate][:demand_group_rates_attributes].present?
        whitelisted[:demand_group_rates_attributes] = params[:demand_source_rate][:demand_group_rates_attributes]
      end
    end
  end
end

app/views/demand_source_rates/edit.html.haml
:javascript
  $(document).ready(function(){
      $("#demand_source_rate_all_groups").click(function(){
          if ($(".group_field").hasClass("hidden")){
              $(".group_field").removeClass("hidden");

              $("#demand_source_rate_rate").attr("required", false);
          } else {
              $(".group_field").addClass("hidden");

              $(".select_group input[type=checkbox]").each(function(){
                $(this).attr("checked", false).change();
              })

              $("#demand_source_rate_rate").attr("required", true);
          }
      });

  });
.container
  - regexp = "([0-9]+[.|,][0-9])|([0-9][.|,][0-9]+)|([0-9]+)"
  = form_for(@source_rate, html: { class: 'form-horizontal well' }) do |f|
    .row
      %table.span5
        %tr
          %th{colspan:2}
            Source:
            = @sources[@source_rate.source]
        %tr
          %td.span1
            = f.label :max_sum, class: "control-label check_box"
          %td.span2
            = f.text_field :max_sum, class: "input-small", required: "required", pattern: regexp
            %i
              ($)
        %tr
          %td.span1
            = f.label :rate, class: "control-label check_box"
          %td.span2
            = f.text_field :rate,  class: "input-small", required: "required", pattern: regexp
            %i
              ($ per posting)
        - if @source_rate.source == "CRAIG"
          %tr
            %td
              = f.label :all_groups, class: "control-label check_box"
            %td
              = f.check_box :all_groups
          = f.fields_for :demand_group_rates do |builder|
            %tr.group_field{ class: "#{ @source_rate.all_groups ? 'hidden' : '' }"}
              %td.span1
                = builder.label :rate, @groups[builder.object.group], class: "control-label"
              %td.span2
                = builder.text_field :rate, class: "input-small", pattern: regexp
                ($ per posting)
      .controls
        = f.submit class: "btn btn-success"

app/views/demand_source_rates/index.html.haml
:scss
  table.table {
    td,th {
      font-size:10px;
    }
    .table_group {
      width: 100%;
      display: table;
      .table_row {
        display: table-row;
        .table_cell {
          display: table-cell;
          padding: 0px 5px;
          text-align: center;
        }
      }
    }
  }
  #direction {
    width: 100px;
  }

.container
  .well
    .span10
      %form.form-inline{ action: demand_source_rates_path, method: 'get' }
        .row
          .span10
            %label.control-label
              Type
              = select_tag "direction", options_for_select([ ['Polling', 'out'], ['Search', 'search'] ], @direction), onchange: 'this.form.submit()'
.row
  %table.table.table-bordered.table-hover.span12
    %thead
      %tr
        %th.span3
          Source
        %th.span2
          Rate
          %i
            ($ per posting)
        %th.span1
          All groups
        %th{style: 'text-align: center'}
          Rates for groups
          %i
            ($ per posting)
          = " / Available groups"
        %th.span2
          Max sum
          %i
            ($)
        %th.span1
    %tbody
    - @available_groups.each do |code, groups|
      %tr
        %td
          = @sources[code]
        %td
          = number_with_delimiter @source_rates[code].rate
        %td
          = @source_rates[code].all_groups ? 'Yes' : 'No'
        %td
          - if code == "CRAIG" && @source_rates[code].all_groups == false
            .table_group
              .table_row
                - @source_rates[code].demand_group_rates.each do |row|
                  .table_cell
                    = @groups[row.group]
                    %br
                    = number_with_delimiter(row.rate)
          - else
            = @groups.select{|code, name| groups.include?(code)}.values.join(", ")
        %td
          = number_with_delimiter @source_rates[code].max_sum
        %td
          = link_to 'Edit', edit_demand_source_rate_path(@source_rates[code]), class: 'btn btn-primary btn-small'